# Generated by Django 4.1.7 on 2023-02-16 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_movies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="movies",
        ),
    ]
