# Generated by Django 4.1.7 on 2023-02-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.CharField(
                choices=[
                    ("G", "Default"),
                    ("PG", "Rated Pg"),
                    ("PG-13", "Rated Pg 13"),
                    ("R", "Rated R"),
                    ("NC-17", "Rated Nc 17"),
                ],
                default="G",
                max_length=20,
            ),
        ),
    ]
